'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class resourcesEnText
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("cems.resourcesEnText", GetType(resourcesEnText).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Equipment hall .
        '''</summary>
        Friend Shared ReadOnly Property addequipmenthalllabel() As String
            Get
                Return ResourceManager.GetString("addequipmenthalllabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Equipment post ID.
        '''</summary>
        Friend Shared ReadOnly Property addequipmentpostidlabel() As String
            Get
                Return ResourceManager.GetString("addequipmentpostidlabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Equipment state .
        '''</summary>
        Friend Shared ReadOnly Property addequipmentstatelabel() As String
            Get
                Return ResourceManager.GetString("addequipmentstatelabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Add equipment.
        '''</summary>
        Friend Shared ReadOnly Property addEquipmentTitle() As String
            Get
                Return ResourceManager.GetString("addEquipmentTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Equipment title.
        '''</summary>
        Friend Shared ReadOnly Property addequipmenttitlelabel() As String
            Get
                Return ResourceManager.GetString("addequipmenttitlelabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Post Hall.
        '''</summary>
        Friend Shared ReadOnly Property addPostHallLabel() As String
            Get
                Return ResourceManager.GetString("addPostHallLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Post ID.
        '''</summary>
        Friend Shared ReadOnly Property addPostIDLabel() As String
            Get
                Return ResourceManager.GetString("addPostIDLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Post state.
        '''</summary>
        Friend Shared ReadOnly Property addPostStateLabel() As String
            Get
                Return ResourceManager.GetString("addPostStateLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Add post.
        '''</summary>
        Friend Shared ReadOnly Property addPostTitle() As String
            Get
                Return ResourceManager.GetString("addPostTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Role name.
        '''</summary>
        Friend Shared ReadOnly Property addRoleNameLabel() As String
            Get
                Return ResourceManager.GetString("addRoleNameLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Add role.
        '''</summary>
        Friend Shared ReadOnly Property addRoleTitle() As String
            Get
                Return ResourceManager.GetString("addRoleTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Confirm Password.
        '''</summary>
        Friend Shared ReadOnly Property addUserConfirmPwdLabel() As String
            Get
                Return ResourceManager.GetString("addUserConfirmPwdLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à User email.
        '''</summary>
        Friend Shared ReadOnly Property addUserEmailLabel() As String
            Get
                Return ResourceManager.GetString("addUserEmailLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à User name.
        '''</summary>
        Friend Shared ReadOnly Property addUserNameLabel() As String
            Get
                Return ResourceManager.GetString("addUserNameLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à User phone number.
        '''</summary>
        Friend Shared ReadOnly Property addUserPhoneLabel() As String
            Get
                Return ResourceManager.GetString("addUserPhoneLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à User Password.
        '''</summary>
        Friend Shared ReadOnly Property addUserPwdLabel() As String
            Get
                Return ResourceManager.GetString("addUserPwdLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à User Title.
        '''</summary>
        Friend Shared ReadOnly Property addUserTitleLabel() As String
            Get
                Return ResourceManager.GetString("addUserTitleLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Confirm Password.
        '''</summary>
        Friend Shared ReadOnly Property adminConfirmPasswordLabel() As String
            Get
                Return ResourceManager.GetString("adminConfirmPasswordLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Admin email.
        '''</summary>
        Friend Shared ReadOnly Property adminEmailLabel() As String
            Get
                Return ResourceManager.GetString("adminEmailLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Home Page.
        '''</summary>
        Friend Shared ReadOnly Property adminHomePage() As String
            Get
                Return ResourceManager.GetString("adminHomePage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Admin name.
        '''</summary>
        Friend Shared ReadOnly Property adminNameLabel() As String
            Get
                Return ResourceManager.GetString("adminNameLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Admin phone number.
        '''</summary>
        Friend Shared ReadOnly Property adminPhoneNumberLabel() As String
            Get
                Return ResourceManager.GetString("adminPhoneNumberLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Admin password .
        '''</summary>
        Friend Shared ReadOnly Property adminPwdLabel() As String
            Get
                Return ResourceManager.GetString("adminPwdLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Equipment state.
        '''</summary>
        Friend Shared ReadOnly Property changeequipmentstatelabel() As String
            Get
                Return ResourceManager.GetString("changeequipmentstatelabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Post hall.
        '''</summary>
        Friend Shared ReadOnly Property changeposthalllabel() As String
            Get
                Return ResourceManager.GetString("changeposthalllabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Post State.
        '''</summary>
        Friend Shared ReadOnly Property changepoststatelabel() As String
            Get
                Return ResourceManager.GetString("changepoststatelabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Equipment successfully added ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgE_add() As String
            Get
                Return ResourceManager.GetString("confirmMsgE_add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Equipment successfully deleted ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgE_delete() As String
            Get
                Return ResourceManager.GetString("confirmMsgE_delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Equipment successfully updated ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgE_update() As String
            Get
                Return ResourceManager.GetString("confirmMsgE_update", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Hall successfully added ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgH_add() As String
            Get
                Return ResourceManager.GetString("confirmMsgH_add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Hall successfully deleted ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgH_delete() As String
            Get
                Return ResourceManager.GetString("confirmMsgH_delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Hall successfully updated ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgH_update() As String
            Get
                Return ResourceManager.GetString("confirmMsgH_update", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Post successfully added ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgP_add() As String
            Get
                Return ResourceManager.GetString("confirmMsgP_add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Post successfully deleted ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgP_delete() As String
            Get
                Return ResourceManager.GetString("confirmMsgP_delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Post successfully updated ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgP_update() As String
            Get
                Return ResourceManager.GetString("confirmMsgP_update", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Profile updated successfully ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgPr() As String
            Get
                Return ResourceManager.GetString("confirmMsgPr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Role successfully added ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgR_add() As String
            Get
                Return ResourceManager.GetString("confirmMsgR_add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Rolel successfully deleted ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgR_delete() As String
            Get
                Return ResourceManager.GetString("confirmMsgR_delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Role successfully updated ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgR_update() As String
            Get
                Return ResourceManager.GetString("confirmMsgR_update", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à User successfully added ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgU_add() As String
            Get
                Return ResourceManager.GetString("confirmMsgU_add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à User successfully deleted ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgU_delete() As String
            Get
                Return ResourceManager.GetString("confirmMsgU_delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à User successfully updated ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgU_update() As String
            Get
                Return ResourceManager.GetString("confirmMsgU_update", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Connect.
        '''</summary>
        Friend Shared ReadOnly Property connectBtn() As String
            Get
                Return ResourceManager.GetString("connectBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Database.
        '''</summary>
        Friend Shared ReadOnly Property connexionDatabaseLabel() As String
            Get
                Return ResourceManager.GetString("connexionDatabaseLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Password.
        '''</summary>
        Friend Shared ReadOnly Property connexionPwdLabel() As String
            Get
                Return ResourceManager.GetString("connexionPwdLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Server.
        '''</summary>
        Friend Shared ReadOnly Property connexionServerLabel() As String
            Get
                Return ResourceManager.GetString("connexionServerLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à User name.
        '''</summary>
        Friend Shared ReadOnly Property connexionUserNameLabel() As String
            Get
                Return ResourceManager.GetString("connexionUserNameLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à CPUs.
        '''</summary>
        Friend Shared ReadOnly Property CPUsBtn() As String
            Get
                Return ResourceManager.GetString("CPUsBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à view.
        '''</summary>
        Friend Shared ReadOnly Property CPUsBtn2() As String
            Get
                Return ResourceManager.GetString("CPUsBtn2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Create admin.
        '''</summary>
        Friend Shared ReadOnly Property createAdminTitle() As String
            Get
                Return ResourceManager.GetString("createAdminTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Dashboard.
        '''</summary>
        Friend Shared ReadOnly Property dashboardBtn() As String
            Get
                Return ResourceManager.GetString("dashboardBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à CPUs.
        '''</summary>
        Friend Shared ReadOnly Property dashboardCPULabel() As String
            Get
                Return ResourceManager.GetString("dashboardCPULabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à IP Phones .
        '''</summary>
        Friend Shared ReadOnly Property dashboardIPLabel() As String
            Get
                Return ResourceManager.GetString("dashboardIPLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Monitors .
        '''</summary>
        Friend Shared ReadOnly Property dashboardMonitorLabel() As String
            Get
                Return ResourceManager.GetString("dashboardMonitorLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à All categories of equipment.
        '''</summary>
        Friend Shared ReadOnly Property dashboardTitle() As String
            Get
                Return ResourceManager.GetString("dashboardTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Users.
        '''</summary>
        Friend Shared ReadOnly Property dashboardUserLabel() As String
            Get
                Return ResourceManager.GetString("dashboardUserLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Users.
        '''</summary>
        Friend Shared ReadOnly Property dashbooardUserLabel() As String
            Get
                Return ResourceManager.GetString("dashbooardUserLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à User email:.
        '''</summary>
        Friend Shared ReadOnly Property EmailProfileLabel() As String
            Get
                Return ResourceManager.GetString("EmailProfileLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Please fill all the fields!.
        '''</summary>
        Friend Shared ReadOnly Property EmptyField() As String
            Get
                Return ResourceManager.GetString("EmptyField", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Add.
        '''</summary>
        Friend Shared ReadOnly Property equipmentAddBtn() As String
            Get
                Return ResourceManager.GetString("equipmentAddBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Cancel.
        '''</summary>
        Friend Shared ReadOnly Property equipmentAddCancelBtn() As String
            Get
                Return ResourceManager.GetString("equipmentAddCancelBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Add.
        '''</summary>
        Friend Shared ReadOnly Property equipmentAddValidationBtn() As String
            Get
                Return ResourceManager.GetString("equipmentAddValidationBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Change.
        '''</summary>
        Friend Shared ReadOnly Property EquipmentChangeBtn() As String
            Get
                Return ResourceManager.GetString("EquipmentChangeBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Delete.
        '''</summary>
        Friend Shared ReadOnly Property equipmentDeleteBtn() As String
            Get
                Return ResourceManager.GetString("equipmentDeleteBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Equipments.
        '''</summary>
        Friend Shared ReadOnly Property equipmentsBtn() As String
            Get
                Return ResourceManager.GetString("equipmentsBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Hall.
        '''</summary>
        Friend Shared ReadOnly Property equipmentsearchhalllabel() As String
            Get
                Return ResourceManager.GetString("equipmentsearchhalllabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Post.
        '''</summary>
        Friend Shared ReadOnly Property equipmentsearchpostidlabel() As String
            Get
                Return ResourceManager.GetString("equipmentsearchpostidlabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à State.
        '''</summary>
        Friend Shared ReadOnly Property equipmentsearchstatelabel() As String
            Get
                Return ResourceManager.GetString("equipmentsearchstatelabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Equipments.
        '''</summary>
        Friend Shared ReadOnly Property equipmentTitle() As String
            Get
                Return ResourceManager.GetString("equipmentTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Add Equipment.
        '''</summary>
        Friend Shared ReadOnly Property EquipmentTitle_Add() As String
            Get
                Return ResourceManager.GetString("EquipmentTitle_Add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à CPUs.
        '''</summary>
        Friend Shared ReadOnly Property EquipmentTitle_CPU() As String
            Get
                Return ResourceManager.GetString("EquipmentTitle_CPU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à IP Phones.
        '''</summary>
        Friend Shared ReadOnly Property EquipmentTitle_IP() As String
            Get
                Return ResourceManager.GetString("EquipmentTitle_IP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Monitors.
        '''</summary>
        Friend Shared ReadOnly Property EquipmentTitle_Monitor() As String
            Get
                Return ResourceManager.GetString("EquipmentTitle_Monitor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Update.
        '''</summary>
        Friend Shared ReadOnly Property equipmentUpdateBtn() As String
            Get
                Return ResourceManager.GetString("equipmentUpdateBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Cancel.
        '''</summary>
        Friend Shared ReadOnly Property equipmentUpdateCancelBtn() As String
            Get
                Return ResourceManager.GetString("equipmentUpdateCancelBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Update.
        '''</summary>
        Friend Shared ReadOnly Property equipmentUpdateValidationBtn() As String
            Get
                Return ResourceManager.GetString("equipmentUpdateValidationBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Export successful ✔.
        '''</summary>
        Friend Shared ReadOnly Property export() As String
            Get
                Return ResourceManager.GetString("export", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Export.
        '''</summary>
        Friend Shared ReadOnly Property exportBtnE() As String
            Get
                Return ResourceManager.GetString("exportBtnE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Export.
        '''</summary>
        Friend Shared ReadOnly Property exportBtnH() As String
            Get
                Return ResourceManager.GetString("exportBtnH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Export.
        '''</summary>
        Friend Shared ReadOnly Property exportBtnP() As String
            Get
                Return ResourceManager.GetString("exportBtnP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Export.
        '''</summary>
        Friend Shared ReadOnly Property exportBtnR() As String
            Get
                Return ResourceManager.GetString("exportBtnR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Export.
        '''</summary>
        Friend Shared ReadOnly Property exportBtnU() As String
            Get
                Return ResourceManager.GetString("exportBtnU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Forgot password ?.
        '''</summary>
        Friend Shared ReadOnly Property forgotPwdBtn() As String
            Get
                Return ResourceManager.GetString("forgotPwdBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Add.
        '''</summary>
        Friend Shared ReadOnly Property hallAddBtn() As String
            Get
                Return ResourceManager.GetString("hallAddBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Cancel.
        '''</summary>
        Friend Shared ReadOnly Property hallAddCancelBtn() As String
            Get
                Return ResourceManager.GetString("hallAddCancelBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Hall Name.
        '''</summary>
        Friend Shared ReadOnly Property hallAddNameLabel() As String
            Get
                Return ResourceManager.GetString("hallAddNameLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Add hall.
        '''</summary>
        Friend Shared ReadOnly Property hallAddTitle() As String
            Get
                Return ResourceManager.GetString("hallAddTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Add.
        '''</summary>
        Friend Shared ReadOnly Property hallAddValidationBtn() As String
            Get
                Return ResourceManager.GetString("hallAddValidationBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Delete.
        '''</summary>
        Friend Shared ReadOnly Property hallDeleteBtn() As String
            Get
                Return ResourceManager.GetString("hallDeleteBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Halls.
        '''</summary>
        Friend Shared ReadOnly Property hallsBtn() As String
            Get
                Return ResourceManager.GetString("hallsBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Hall.
        '''</summary>
        Friend Shared ReadOnly Property hallSearchLabel() As String
            Get
                Return ResourceManager.GetString("hallSearchLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Hall.
        '''</summary>
        Friend Shared ReadOnly Property hallSearchLabelE() As String
            Get
                Return ResourceManager.GetString("hallSearchLabelE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à search Hall.
        '''</summary>
        Friend Shared ReadOnly Property hallSearchLabelH() As String
            Get
                Return ResourceManager.GetString("hallSearchLabelH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Hall.
        '''</summary>
        Friend Shared ReadOnly Property hallSearchLabelP() As String
            Get
                Return ResourceManager.GetString("hallSearchLabelP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Halls.
        '''</summary>
        Friend Shared ReadOnly Property hallTitle() As String
            Get
                Return ResourceManager.GetString("hallTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Add hall.
        '''</summary>
        Friend Shared ReadOnly Property hallTitle_Add() As String
            Get
                Return ResourceManager.GetString("hallTitle_Add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Update hall.
        '''</summary>
        Friend Shared ReadOnly Property hallTitle_Update() As String
            Get
                Return ResourceManager.GetString("hallTitle_Update", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Update.
        '''</summary>
        Friend Shared ReadOnly Property hallUpdateBtn() As String
            Get
                Return ResourceManager.GetString("hallUpdateBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Cancel.
        '''</summary>
        Friend Shared ReadOnly Property hallUpdateCancelBtn() As String
            Get
                Return ResourceManager.GetString("hallUpdateCancelBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Hall Name.
        '''</summary>
        Friend Shared ReadOnly Property hallUpdateNameLabel() As String
            Get
                Return ResourceManager.GetString("hallUpdateNameLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Update hall.
        '''</summary>
        Friend Shared ReadOnly Property hallUpdateTitle() As String
            Get
                Return ResourceManager.GetString("hallUpdateTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Update.
        '''</summary>
        Friend Shared ReadOnly Property hallUpdateValidationBtn() As String
            Get
                Return ResourceManager.GetString("hallUpdateValidationBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à your connexion string is not valid check your information!.
        '''</summary>
        Friend Shared ReadOnly Property InvalidConnectionString() As String
            Get
                Return ResourceManager.GetString("InvalidConnectionString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Invalid email format!.
        '''</summary>
        Friend Shared ReadOnly Property invalidEmail() As String
            Get
                Return ResourceManager.GetString("invalidEmail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à IP Phones.
        '''</summary>
        Friend Shared ReadOnly Property IPsBtn() As String
            Get
                Return ResourceManager.GetString("IPsBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à view.
        '''</summary>
        Friend Shared ReadOnly Property IPsBtn2() As String
            Get
                Return ResourceManager.GetString("IPsBtn2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Login.
        '''</summary>
        Friend Shared ReadOnly Property loginBtn() As String
            Get
                Return ResourceManager.GetString("loginBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à login with the admin account information ✔.
        '''</summary>
        Friend Shared ReadOnly Property LoginSuccess() As String
            Get
                Return ResourceManager.GetString("LoginSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Login.
        '''</summary>
        Friend Shared ReadOnly Property loginTitle() As String
            Get
                Return ResourceManager.GetString("loginTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Email.
        '''</summary>
        Friend Shared ReadOnly Property loginUserEmailLabel() As String
            Get
                Return ResourceManager.GetString("loginUserEmailLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Password.
        '''</summary>
        Friend Shared ReadOnly Property loginUserPwdLabel() As String
            Get
                Return ResourceManager.GetString("loginUserPwdLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Logout.
        '''</summary>
        Friend Shared ReadOnly Property logoutBtn() As String
            Get
                Return ResourceManager.GetString("logoutBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Monitors.
        '''</summary>
        Friend Shared ReadOnly Property monitorsBtn() As String
            Get
                Return ResourceManager.GetString("monitorsBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à view.
        '''</summary>
        Friend Shared ReadOnly Property monitorsBtn2() As String
            Get
                Return ResourceManager.GetString("monitorsBtn2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à User name:.
        '''</summary>
        Friend Shared ReadOnly Property NameProfileLabel() As String
            Get
                Return ResourceManager.GetString("NameProfileLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à User Phone number:.
        '''</summary>
        Friend Shared ReadOnly Property PhoneNumberProfileLabel() As String
            Get
                Return ResourceManager.GetString("PhoneNumberProfileLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Add.
        '''</summary>
        Friend Shared ReadOnly Property postAddBtn() As String
            Get
                Return ResourceManager.GetString("postAddBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Cancel.
        '''</summary>
        Friend Shared ReadOnly Property postAddCancelBtn() As String
            Get
                Return ResourceManager.GetString("postAddCancelBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Add.
        '''</summary>
        Friend Shared ReadOnly Property postAddValidationBtn() As String
            Get
                Return ResourceManager.GetString("postAddValidationBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Change.
        '''</summary>
        Friend Shared ReadOnly Property postChangeBtn() As String
            Get
                Return ResourceManager.GetString("postChangeBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Delete.
        '''</summary>
        Friend Shared ReadOnly Property postDeleteBtn() As String
            Get
                Return ResourceManager.GetString("postDeleteBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Post already exist try adding another one!.
        '''</summary>
        Friend Shared ReadOnly Property postExist() As String
            Get
                Return ResourceManager.GetString("postExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Posts.
        '''</summary>
        Friend Shared ReadOnly Property postsBtn() As String
            Get
                Return ResourceManager.GetString("postsBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Post.
        '''</summary>
        Friend Shared ReadOnly Property postsearchlabel() As String
            Get
                Return ResourceManager.GetString("postsearchlabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Posts.
        '''</summary>
        Friend Shared ReadOnly Property postTitle() As String
            Get
                Return ResourceManager.GetString("postTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Add post.
        '''</summary>
        Friend Shared ReadOnly Property postTitle_Add() As String
            Get
                Return ResourceManager.GetString("postTitle_Add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Update.
        '''</summary>
        Friend Shared ReadOnly Property postUpdateBtn() As String
            Get
                Return ResourceManager.GetString("postUpdateBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Cancel.
        '''</summary>
        Friend Shared ReadOnly Property postUpdateCancelBtn() As String
            Get
                Return ResourceManager.GetString("postUpdateCancelBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Update.
        '''</summary>
        Friend Shared ReadOnly Property postUpdateValidationBtn() As String
            Get
                Return ResourceManager.GetString("postUpdateValidationBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Profile.
        '''</summary>
        Friend Shared ReadOnly Property profileBtn() As String
            Get
                Return ResourceManager.GetString("profileBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Profile.
        '''</summary>
        Friend Shared ReadOnly Property profileTitle() As String
            Get
                Return ResourceManager.GetString("profileTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Update profile.
        '''</summary>
        Friend Shared ReadOnly Property profileTitle_Update() As String
            Get
                Return ResourceManager.GetString("profileTitle_Update", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Please enter the same password!.
        '''</summary>
        Friend Shared ReadOnly Property PwdNotMatch() As String
            Get
                Return ResourceManager.GetString("PwdNotMatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Refresh.
        '''</summary>
        Friend Shared ReadOnly Property refreshBtnE() As String
            Get
                Return ResourceManager.GetString("refreshBtnE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Refresh.
        '''</summary>
        Friend Shared ReadOnly Property refreshBtnH() As String
            Get
                Return ResourceManager.GetString("refreshBtnH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Refresh.
        '''</summary>
        Friend Shared ReadOnly Property refreshBtnP() As String
            Get
                Return ResourceManager.GetString("refreshBtnP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Refresh.
        '''</summary>
        Friend Shared ReadOnly Property refreshBtnR() As String
            Get
                Return ResourceManager.GetString("refreshBtnR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Refresh.
        '''</summary>
        Friend Shared ReadOnly Property refreshBtnU() As String
            Get
                Return ResourceManager.GetString("refreshBtnU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Add.
        '''</summary>
        Friend Shared ReadOnly Property roleAddBtn() As String
            Get
                Return ResourceManager.GetString("roleAddBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Cancel.
        '''</summary>
        Friend Shared ReadOnly Property roleAddCancelBtn() As String
            Get
                Return ResourceManager.GetString("roleAddCancelBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Add.
        '''</summary>
        Friend Shared ReadOnly Property roleAddValidationBtn() As String
            Get
                Return ResourceManager.GetString("roleAddValidationBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Delete.
        '''</summary>
        Friend Shared ReadOnly Property roleDeleteBtn() As String
            Get
                Return ResourceManager.GetString("roleDeleteBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Roles.
        '''</summary>
        Friend Shared ReadOnly Property rolesBtn() As String
            Get
                Return ResourceManager.GetString("rolesBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Roles.
        '''</summary>
        Friend Shared ReadOnly Property roleTitle() As String
            Get
                Return ResourceManager.GetString("roleTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Add role.
        '''</summary>
        Friend Shared ReadOnly Property roleTitle_Add() As String
            Get
                Return ResourceManager.GetString("roleTitle_Add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Update role.
        '''</summary>
        Friend Shared ReadOnly Property roleTitle_Update() As String
            Get
                Return ResourceManager.GetString("roleTitle_Update", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Update.
        '''</summary>
        Friend Shared ReadOnly Property roleUpdateBtn() As String
            Get
                Return ResourceManager.GetString("roleUpdateBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Cancel.
        '''</summary>
        Friend Shared ReadOnly Property roleUpdateCancelBtn() As String
            Get
                Return ResourceManager.GetString("roleUpdateCancelBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Update.
        '''</summary>
        Friend Shared ReadOnly Property roleUpdateValidationBtn() As String
            Get
                Return ResourceManager.GetString("roleUpdateValidationBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à No result found.
        '''</summary>
        Friend Shared ReadOnly Property searchErrorE() As String
            Get
                Return ResourceManager.GetString("searchErrorE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à No result found.
        '''</summary>
        Friend Shared ReadOnly Property searchErrorH() As String
            Get
                Return ResourceManager.GetString("searchErrorH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à No result found.
        '''</summary>
        Friend Shared ReadOnly Property searchErrorP() As String
            Get
                Return ResourceManager.GetString("searchErrorP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à No result found.
        '''</summary>
        Friend Shared ReadOnly Property searchErrorR() As String
            Get
                Return ResourceManager.GetString("searchErrorR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à No result found.
        '''</summary>
        Friend Shared ReadOnly Property searchErrorU() As String
            Get
                Return ResourceManager.GetString("searchErrorU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Search username.
        '''</summary>
        Friend Shared ReadOnly Property searchUserLabel() As String
            Get
                Return ResourceManager.GetString("searchUserLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à State.
        '''</summary>
        Friend Shared ReadOnly Property statesearchlabel() As String
            Get
                Return ResourceManager.GetString("statesearchlabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à .
        '''</summary>
        Friend Shared ReadOnly Property sttring() As String
            Get
                Return ResourceManager.GetString("sttring", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à User Title:.
        '''</summary>
        Friend Shared ReadOnly Property TitleProfileLabel() As String
            Get
                Return ResourceManager.GetString("TitleProfileLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Update equipment.
        '''</summary>
        Friend Shared ReadOnly Property updateEquipmentTitle() As String
            Get
                Return ResourceManager.GetString("updateEquipmentTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Update post.
        '''</summary>
        Friend Shared ReadOnly Property updatePostTitle() As String
            Get
                Return ResourceManager.GetString("updatePostTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Cancel.
        '''</summary>
        Friend Shared ReadOnly Property updateProfileCancelBtn() As String
            Get
                Return ResourceManager.GetString("updateProfileCancelBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Update.
        '''</summary>
        Friend Shared ReadOnly Property updateProfileShowBtn() As String
            Get
                Return ResourceManager.GetString("updateProfileShowBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Update Profile.
        '''</summary>
        Friend Shared ReadOnly Property updateProfileTitle() As String
            Get
                Return ResourceManager.GetString("updateProfileTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Update.
        '''</summary>
        Friend Shared ReadOnly Property updateProfileValidationBtn() As String
            Get
                Return ResourceManager.GetString("updateProfileValidationBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Please fill the field.
        '''</summary>
        Friend Shared ReadOnly Property updateRoleErrorMsg() As String
            Get
                Return ResourceManager.GetString("updateRoleErrorMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Role name.
        '''</summary>
        Friend Shared ReadOnly Property updateRoleNameLabel() As String
            Get
                Return ResourceManager.GetString("updateRoleNameLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Update role.
        '''</summary>
        Friend Shared ReadOnly Property updateRoleTitle() As String
            Get
                Return ResourceManager.GetString("updateRoleTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à User email.
        '''</summary>
        Friend Shared ReadOnly Property updateUserEmailLabel() As String
            Get
                Return ResourceManager.GetString("updateUserEmailLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à User name.
        '''</summary>
        Friend Shared ReadOnly Property updateUserNameLabel() As String
            Get
                Return ResourceManager.GetString("updateUserNameLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à User phone number.
        '''</summary>
        Friend Shared ReadOnly Property updateUserPhoneLabel() As String
            Get
                Return ResourceManager.GetString("updateUserPhoneLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Update User.
        '''</summary>
        Friend Shared ReadOnly Property updateUserTitle() As String
            Get
                Return ResourceManager.GetString("updateUserTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à User Title.
        '''</summary>
        Friend Shared ReadOnly Property updateUserTitleLabel() As String
            Get
                Return ResourceManager.GetString("updateUserTitleLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Add.
        '''</summary>
        Friend Shared ReadOnly Property userAddBtn() As String
            Get
                Return ResourceManager.GetString("userAddBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Cancel.
        '''</summary>
        Friend Shared ReadOnly Property userAddCancelBtn() As String
            Get
                Return ResourceManager.GetString("userAddCancelBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Add.
        '''</summary>
        Friend Shared ReadOnly Property userAddValidationBtn() As String
            Get
                Return ResourceManager.GetString("userAddValidationBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Confirm Password.
        '''</summary>
        Friend Shared ReadOnly Property userConfirmPwdProfileLabel2() As String
            Get
                Return ResourceManager.GetString("userConfirmPwdProfileLabel2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Delete.
        '''</summary>
        Friend Shared ReadOnly Property userDeleteBtn() As String
            Get
                Return ResourceManager.GetString("userDeleteBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à User email.
        '''</summary>
        Friend Shared ReadOnly Property userEmailProfileLabel2() As String
            Get
                Return ResourceManager.GetString("userEmailProfileLabel2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à User already exist try adding another one!.
        '''</summary>
        Friend Shared ReadOnly Property userExist() As String
            Get
                Return ResourceManager.GetString("userExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à User name.
        '''</summary>
        Friend Shared ReadOnly Property userNameProfileLabel2() As String
            Get
                Return ResourceManager.GetString("userNameProfileLabel2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à User phone number.
        '''</summary>
        Friend Shared ReadOnly Property userPhoneNumberProfileLabel2() As String
            Get
                Return ResourceManager.GetString("userPhoneNumberProfileLabel2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Enter new password.
        '''</summary>
        Friend Shared ReadOnly Property userPwdProfileLabel2() As String
            Get
                Return ResourceManager.GetString("userPwdProfileLabel2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Users.
        '''</summary>
        Friend Shared ReadOnly Property usersBtn() As String
            Get
                Return ResourceManager.GetString("usersBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à view.
        '''</summary>
        Friend Shared ReadOnly Property usersBtn2() As String
            Get
                Return ResourceManager.GetString("usersBtn2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Users.
        '''</summary>
        Friend Shared ReadOnly Property userTitle() As String
            Get
                Return ResourceManager.GetString("userTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Add user.
        '''</summary>
        Friend Shared ReadOnly Property userTitle_Add() As String
            Get
                Return ResourceManager.GetString("userTitle_Add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Update user.
        '''</summary>
        Friend Shared ReadOnly Property userTitle_Update() As String
            Get
                Return ResourceManager.GetString("userTitle_Update", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Admin.
        '''</summary>
        Friend Shared ReadOnly Property userTypeTitle() As String
            Get
                Return ResourceManager.GetString("userTypeTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Users.
        '''</summary>
        Friend Shared ReadOnly Property userTypeTitleU() As String
            Get
                Return ResourceManager.GetString("userTypeTitleU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Update.
        '''</summary>
        Friend Shared ReadOnly Property userUpdateBtn() As String
            Get
                Return ResourceManager.GetString("userUpdateBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Cancel.
        '''</summary>
        Friend Shared ReadOnly Property userUpdateCancelBtn() As String
            Get
                Return ResourceManager.GetString("userUpdateCancelBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Update.
        '''</summary>
        Friend Shared ReadOnly Property userUpdateValidationBtn() As String
            Get
                Return ResourceManager.GetString("userUpdateValidationBtn", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
