'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class resourcesFrText
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("cems.resourcesFrText", GetType(resourcesFrText).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ajouter.
        '''</summary>
        Friend Shared ReadOnly Property addEquipmentBtn() As String
            Get
                Return ResourceManager.GetString("addEquipmentBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Annuler.
        '''</summary>
        Friend Shared ReadOnly Property addEquipmentCancelBtn() As String
            Get
                Return ResourceManager.GetString("addEquipmentCancelBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Salle de l&apos;équipement.
        '''</summary>
        Friend Shared ReadOnly Property addequipmenthalllabel() As String
            Get
                Return ResourceManager.GetString("addequipmenthalllabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à ID du poste de l&apos;équipement.
        '''</summary>
        Friend Shared ReadOnly Property addequipmentpostidlabel() As String
            Get
                Return ResourceManager.GetString("addequipmentpostidlabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à État de l&apos;équipement.
        '''</summary>
        Friend Shared ReadOnly Property addequipmentstatelabel() As String
            Get
                Return ResourceManager.GetString("addequipmentstatelabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ajouter un équipement.
        '''</summary>
        Friend Shared ReadOnly Property addEquipmentTitle() As String
            Get
                Return ResourceManager.GetString("addEquipmentTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Titre de l&apos;équipement.
        '''</summary>
        Friend Shared ReadOnly Property addequipmenttitlelabel() As String
            Get
                Return ResourceManager.GetString("addequipmenttitlelabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ajouter.
        '''</summary>
        Friend Shared ReadOnly Property addEquipmentValidationBtn() As String
            Get
                Return ResourceManager.GetString("addEquipmentValidationBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez remplir tous les champs!.
        '''</summary>
        Friend Shared ReadOnly Property addHallErrorMsg() As String
            Get
                Return ResourceManager.GetString("addHallErrorMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nom de la salle.
        '''</summary>
        Friend Shared ReadOnly Property addHallNameLabel() As String
            Get
                Return ResourceManager.GetString("addHallNameLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ajouter.
        '''</summary>
        Friend Shared ReadOnly Property addPostBtn() As String
            Get
                Return ResourceManager.GetString("addPostBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Annuler.
        '''</summary>
        Friend Shared ReadOnly Property addPostCancelBtn() As String
            Get
                Return ResourceManager.GetString("addPostCancelBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Salle du poste.
        '''</summary>
        Friend Shared ReadOnly Property addPostHallLabel() As String
            Get
                Return ResourceManager.GetString("addPostHallLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à ID du poste.
        '''</summary>
        Friend Shared ReadOnly Property addPostIDLabel() As String
            Get
                Return ResourceManager.GetString("addPostIDLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à État de poste.
        '''</summary>
        Friend Shared ReadOnly Property addPostStateLabel() As String
            Get
                Return ResourceManager.GetString("addPostStateLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ajouter un poste.
        '''</summary>
        Friend Shared ReadOnly Property addPostTitle() As String
            Get
                Return ResourceManager.GetString("addPostTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ajouter.
        '''</summary>
        Friend Shared ReadOnly Property addPostValidationBtn() As String
            Get
                Return ResourceManager.GetString("addPostValidationBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez remplir le champ!.
        '''</summary>
        Friend Shared ReadOnly Property addRoleErrorMsg() As String
            Get
                Return ResourceManager.GetString("addRoleErrorMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nom du Rôle.
        '''</summary>
        Friend Shared ReadOnly Property addRoleNameLabel() As String
            Get
                Return ResourceManager.GetString("addRoleNameLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ajouter un rôle.
        '''</summary>
        Friend Shared ReadOnly Property addRoleTitle() As String
            Get
                Return ResourceManager.GetString("addRoleTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Confirmez le mot de passe.
        '''</summary>
        Friend Shared ReadOnly Property addUserConfirmPwdLabel() As String
            Get
                Return ResourceManager.GetString("addUserConfirmPwdLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Courriel de l&apos;utilisateur.
        '''</summary>
        Friend Shared ReadOnly Property addUserEmailLabel() As String
            Get
                Return ResourceManager.GetString("addUserEmailLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez remplir tous les champs.
        '''</summary>
        Friend Shared ReadOnly Property addUserErrorMsg_EmptyField() As String
            Get
                Return ResourceManager.GetString("addUserErrorMsg.EmptyField", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez saisir le même mot de passe !.
        '''</summary>
        Friend Shared ReadOnly Property addUserErrorMsg_PwdNotMatch() As String
            Get
                Return ResourceManager.GetString("addUserErrorMsg.PwdNotMatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nom de l&apos;utilisateur.
        '''</summary>
        Friend Shared ReadOnly Property addUserNameLabel() As String
            Get
                Return ResourceManager.GetString("addUserNameLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Numéro de téléphone de l&apos;utilisateur.
        '''</summary>
        Friend Shared ReadOnly Property addUserPhoneLabel() As String
            Get
                Return ResourceManager.GetString("addUserPhoneLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mot de passe de l&apos;utilisateur.
        '''</summary>
        Friend Shared ReadOnly Property addUserPwdLabel() As String
            Get
                Return ResourceManager.GetString("addUserPwdLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Titre de l&apos;utilisateur.
        '''</summary>
        Friend Shared ReadOnly Property addUserTitle() As String
            Get
                Return ResourceManager.GetString("addUserTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Confirmez le mot de passe.
        '''</summary>
        Friend Shared ReadOnly Property adminConfirmPasswordLabel() As String
            Get
                Return ResourceManager.GetString("adminConfirmPasswordLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Courriel de l&apos;administrateur.
        '''</summary>
        Friend Shared ReadOnly Property adminEmailLabel() As String
            Get
                Return ResourceManager.GetString("adminEmailLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Page d&apos;accueil.
        '''</summary>
        Friend Shared ReadOnly Property adminHomePage() As String
            Get
                Return ResourceManager.GetString("adminHomePage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nom de l&apos;administrateur.
        '''</summary>
        Friend Shared ReadOnly Property adminNameLabel() As String
            Get
                Return ResourceManager.GetString("adminNameLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Numéro de téléphone de l&apos;administrateur.
        '''</summary>
        Friend Shared ReadOnly Property adminPhoneNumberLabel() As String
            Get
                Return ResourceManager.GetString("adminPhoneNumberLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mot de passe administrateur.
        '''</summary>
        Friend Shared ReadOnly Property adminPwdLabel() As String
            Get
                Return ResourceManager.GetString("adminPwdLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à État de l&apos;équipement.
        '''</summary>
        Friend Shared ReadOnly Property changeequipmentstatelabel() As String
            Get
                Return ResourceManager.GetString("changeequipmentstatelabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à État du poste.
        '''</summary>
        Friend Shared ReadOnly Property changepoststatelabel() As String
            Get
                Return ResourceManager.GetString("changepoststatelabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à équipement ajouté avec succès ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgE_text_add() As String
            Get
                Return ResourceManager.GetString("confirmMsgE.text.add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à équipement supprimée avec succès ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgE_text_delete() As String
            Get
                Return ResourceManager.GetString("confirmMsgE.text.delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Exportation réussie ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgE_text_export() As String
            Get
                Return ResourceManager.GetString("confirmMsgE.text.export", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à équipement mise à jour avec succès ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgE_text_update() As String
            Get
                Return ResourceManager.GetString("confirmMsgE.text.update", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Salle ajoutée avec succès ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgH_text_add() As String
            Get
                Return ResourceManager.GetString("confirmMsgH.text.add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Salle supprimée avec succès ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgH_text_delete() As String
            Get
                Return ResourceManager.GetString("confirmMsgH.text.delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Exportation réussie ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgH_text_export() As String
            Get
                Return ResourceManager.GetString("confirmMsgH.text.export", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Salle ajoutée avec succès ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgH_text_update() As String
            Get
                Return ResourceManager.GetString("confirmMsgH.text.update", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Poste ajouté avec succès ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgP_text_add() As String
            Get
                Return ResourceManager.GetString("confirmMsgP.text.add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Poste supprimée avec succès ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgP_text_delete() As String
            Get
                Return ResourceManager.GetString("confirmMsgP.text.delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Exportation réussie ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgP_text_export() As String
            Get
                Return ResourceManager.GetString("confirmMsgP.text.export", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Poste mise à jour avec succès ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgP_text_update() As String
            Get
                Return ResourceManager.GetString("confirmMsgP.text.update", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Profile updated successfully.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgPr() As String
            Get
                Return ResourceManager.GetString("confirmMsgPr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à rôle ajouté avec succès ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgR_text_add() As String
            Get
                Return ResourceManager.GetString("confirmMsgR.text.add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à rôle supprimée avec succès ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgR_text_delete() As String
            Get
                Return ResourceManager.GetString("confirmMsgR.text.delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Exportation réussie ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgR_text_export() As String
            Get
                Return ResourceManager.GetString("confirmMsgR.text.export", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Rôle mise à jour avec succès ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgR_text_update() As String
            Get
                Return ResourceManager.GetString("confirmMsgR.text.update", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Utilisateur ajouté avec succès ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgU_text_add() As String
            Get
                Return ResourceManager.GetString("confirmMsgU.text.add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Utisateur supprimée avec succès ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgU_text_delete() As String
            Get
                Return ResourceManager.GetString("confirmMsgU.text.delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Exportation réussie ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgU_text_export() As String
            Get
                Return ResourceManager.GetString("confirmMsgU.text.export", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Utilisateur mise à jour avec succès ✔.
        '''</summary>
        Friend Shared ReadOnly Property confirmMsgU_text_update() As String
            Get
                Return ResourceManager.GetString("confirmMsgU.text.update", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Connecter.
        '''</summary>
        Friend Shared ReadOnly Property connectBtn() As String
            Get
                Return ResourceManager.GetString("connectBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Base de donné.
        '''</summary>
        Friend Shared ReadOnly Property connexionDatabaseLabel() As String
            Get
                Return ResourceManager.GetString("connexionDatabaseLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mot de passe.
        '''</summary>
        Friend Shared ReadOnly Property connexionPwdLabel() As String
            Get
                Return ResourceManager.GetString("connexionPwdLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Serveur.
        '''</summary>
        Friend Shared ReadOnly Property connexionServerLabel() As String
            Get
                Return ResourceManager.GetString("connexionServerLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nom de l&apos;utitsateur.
        '''</summary>
        Friend Shared ReadOnly Property connexionUserNameLabel() As String
            Get
                Return ResourceManager.GetString("connexionUserNameLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Unités centrales.
        '''</summary>
        Friend Shared ReadOnly Property CPUsBtn() As String
            Get
                Return ResourceManager.GetString("CPUsBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Voir.
        '''</summary>
        Friend Shared ReadOnly Property CPUsBtn2() As String
            Get
                Return ResourceManager.GetString("CPUsBtn2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Créer un administrateur.
        '''</summary>
        Friend Shared ReadOnly Property createAdminTitle() As String
            Get
                Return ResourceManager.GetString("createAdminTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Tableau de bord.
        '''</summary>
        Friend Shared ReadOnly Property dashboardBtn() As String
            Get
                Return ResourceManager.GetString("dashboardBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Unités centrales.
        '''</summary>
        Friend Shared ReadOnly Property dashboardCPULabel() As String
            Get
                Return ResourceManager.GetString("dashboardCPULabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Téléphones IP.
        '''</summary>
        Friend Shared ReadOnly Property dashboardIPLabel() As String
            Get
                Return ResourceManager.GetString("dashboardIPLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Moniteurs.
        '''</summary>
        Friend Shared ReadOnly Property dashboardMonitorLabel() As String
            Get
                Return ResourceManager.GetString("dashboardMonitorLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Toutes les catégories d&apos;équipements.
        '''</summary>
        Friend Shared ReadOnly Property dashboardTitle() As String
            Get
                Return ResourceManager.GetString("dashboardTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Utilisateurs.
        '''</summary>
        Friend Shared ReadOnly Property dashboardUserLabel() As String
            Get
                Return ResourceManager.GetString("dashboardUserLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Utilisateurs.
        '''</summary>
        Friend Shared ReadOnly Property dashbooardUserLabel() As String
            Get
                Return ResourceManager.GetString("dashbooardUserLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à E-mail de l&apos;utilisateur:.
        '''</summary>
        Friend Shared ReadOnly Property EmailProfileLabel() As String
            Get
                Return ResourceManager.GetString("EmailProfileLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Changer.
        '''</summary>
        Friend Shared ReadOnly Property EquipmentChangeBtn() As String
            Get
                Return ResourceManager.GetString("EquipmentChangeBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Supprimer.
        '''</summary>
        Friend Shared ReadOnly Property equipmentDeleteBtn() As String
            Get
                Return ResourceManager.GetString("equipmentDeleteBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Équipements.
        '''</summary>
        Friend Shared ReadOnly Property equipmentsBtn() As String
            Get
                Return ResourceManager.GetString("equipmentsBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Salle.
        '''</summary>
        Friend Shared ReadOnly Property equipmentsearchhalllabel() As String
            Get
                Return ResourceManager.GetString("equipmentsearchhalllabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Poste.
        '''</summary>
        Friend Shared ReadOnly Property equipmentsearchpostidlabel() As String
            Get
                Return ResourceManager.GetString("equipmentsearchpostidlabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à État.
        '''</summary>
        Friend Shared ReadOnly Property equipmentsearchstatelabel() As String
            Get
                Return ResourceManager.GetString("equipmentsearchstatelabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Équipements.
        '''</summary>
        Friend Shared ReadOnly Property equipmentTitle() As String
            Get
                Return ResourceManager.GetString("equipmentTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mettre à jour.
        '''</summary>
        Friend Shared ReadOnly Property equipmentUpdateBtn() As String
            Get
                Return ResourceManager.GetString("equipmentUpdateBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Annuler.
        '''</summary>
        Friend Shared ReadOnly Property equipmentUpdateCancelBtn() As String
            Get
                Return ResourceManager.GetString("equipmentUpdateCancelBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mettre à jour.
        '''</summary>
        Friend Shared ReadOnly Property equipmentUpdateValidationBtn() As String
            Get
                Return ResourceManager.GetString("equipmentUpdateValidationBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Exporter.
        '''</summary>
        Friend Shared ReadOnly Property exportBtnE() As String
            Get
                Return ResourceManager.GetString("exportBtnE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Exporter.
        '''</summary>
        Friend Shared ReadOnly Property exportBtnH() As String
            Get
                Return ResourceManager.GetString("exportBtnH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Exporter.
        '''</summary>
        Friend Shared ReadOnly Property exportBtnP() As String
            Get
                Return ResourceManager.GetString("exportBtnP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Exporter.
        '''</summary>
        Friend Shared ReadOnly Property exportBtnR() As String
            Get
                Return ResourceManager.GetString("exportBtnR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Exporter.
        '''</summary>
        Friend Shared ReadOnly Property exportBtnU() As String
            Get
                Return ResourceManager.GetString("exportBtnU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mot de passe oublié?.
        '''</summary>
        Friend Shared ReadOnly Property forgotPwdBtn() As String
            Get
                Return ResourceManager.GetString("forgotPwdBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ajouter.
        '''</summary>
        Friend Shared ReadOnly Property hallAddBtn() As String
            Get
                Return ResourceManager.GetString("hallAddBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Annuler.
        '''</summary>
        Friend Shared ReadOnly Property hallAddCancelBtn() As String
            Get
                Return ResourceManager.GetString("hallAddCancelBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nom de la salle.
        '''</summary>
        Friend Shared ReadOnly Property hallAddNameLabel() As String
            Get
                Return ResourceManager.GetString("hallAddNameLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ajouter une salle .
        '''</summary>
        Friend Shared ReadOnly Property hallAddTitle() As String
            Get
                Return ResourceManager.GetString("hallAddTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ajouter.
        '''</summary>
        Friend Shared ReadOnly Property hallAddValidationBtn() As String
            Get
                Return ResourceManager.GetString("hallAddValidationBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Supprimer.
        '''</summary>
        Friend Shared ReadOnly Property hallDeleteBtn() As String
            Get
                Return ResourceManager.GetString("hallDeleteBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Salles.
        '''</summary>
        Friend Shared ReadOnly Property hallsBtn() As String
            Get
                Return ResourceManager.GetString("hallsBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Salle.
        '''</summary>
        Friend Shared ReadOnly Property hallsearchlabel() As String
            Get
                Return ResourceManager.GetString("hallsearchlabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Salle.
        '''</summary>
        Friend Shared ReadOnly Property hallSearchLabelE() As String
            Get
                Return ResourceManager.GetString("hallSearchLabelE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Recherche salle.
        '''</summary>
        Friend Shared ReadOnly Property hallSearchLabelH() As String
            Get
                Return ResourceManager.GetString("hallSearchLabelH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Salle.
        '''</summary>
        Friend Shared ReadOnly Property hallSearchLabelP() As String
            Get
                Return ResourceManager.GetString("hallSearchLabelP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Salles.
        '''</summary>
        Friend Shared ReadOnly Property hallTitle() As String
            Get
                Return ResourceManager.GetString("hallTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mettre à jour.
        '''</summary>
        Friend Shared ReadOnly Property hallUpdateBtn() As String
            Get
                Return ResourceManager.GetString("hallUpdateBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Annuler.
        '''</summary>
        Friend Shared ReadOnly Property hallUpdateCancelBtn() As String
            Get
                Return ResourceManager.GetString("hallUpdateCancelBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nom de salle.
        '''</summary>
        Friend Shared ReadOnly Property hallUpdateNameLabel() As String
            Get
                Return ResourceManager.GetString("hallUpdateNameLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mettre la salle à jour.
        '''</summary>
        Friend Shared ReadOnly Property hallUpdateTitle() As String
            Get
                Return ResourceManager.GetString("hallUpdateTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à mettre à jour.
        '''</summary>
        Friend Shared ReadOnly Property hallUpdateValidationBtn() As String
            Get
                Return ResourceManager.GetString("hallUpdateValidationBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Téléphones IP.
        '''</summary>
        Friend Shared ReadOnly Property IPsBtn() As String
            Get
                Return ResourceManager.GetString("IPsBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Voir.
        '''</summary>
        Friend Shared ReadOnly Property IPsBtn2() As String
            Get
                Return ResourceManager.GetString("IPsBtn2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Se connecter.
        '''</summary>
        Friend Shared ReadOnly Property loginBtn() As String
            Get
                Return ResourceManager.GetString("loginBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Se connecter.
        '''</summary>
        Friend Shared ReadOnly Property loginTitle() As String
            Get
                Return ResourceManager.GetString("loginTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à E-mail.
        '''</summary>
        Friend Shared ReadOnly Property loginUserEmailLabel() As String
            Get
                Return ResourceManager.GetString("loginUserEmailLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mot de passe.
        '''</summary>
        Friend Shared ReadOnly Property loginUserPwdLabel() As String
            Get
                Return ResourceManager.GetString("loginUserPwdLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Se déconnecter.
        '''</summary>
        Friend Shared ReadOnly Property logoutBtn() As String
            Get
                Return ResourceManager.GetString("logoutBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Moniteurs.
        '''</summary>
        Friend Shared ReadOnly Property monitorsBtn() As String
            Get
                Return ResourceManager.GetString("monitorsBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Voir.
        '''</summary>
        Friend Shared ReadOnly Property monitorsBtn2() As String
            Get
                Return ResourceManager.GetString("monitorsBtn2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nom de l&apos;utilisateur:.
        '''</summary>
        Friend Shared ReadOnly Property NameProfileLabel() As String
            Get
                Return ResourceManager.GetString("NameProfileLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Numéro de téléphone de l&apos;utilisateur:.
        '''</summary>
        Friend Shared ReadOnly Property PhoneNumberProfileLabel() As String
            Get
                Return ResourceManager.GetString("PhoneNumberProfileLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ajouter.
        '''</summary>
        Friend Shared ReadOnly Property postAddBtn() As String
            Get
                Return ResourceManager.GetString("postAddBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Annuler.
        '''</summary>
        Friend Shared ReadOnly Property postAddCancelBtn() As String
            Get
                Return ResourceManager.GetString("postAddCancelBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ajouter.
        '''</summary>
        Friend Shared ReadOnly Property postAddValidationBtn() As String
            Get
                Return ResourceManager.GetString("postAddValidationBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Changer.
        '''</summary>
        Friend Shared ReadOnly Property postChangeBtn() As String
            Get
                Return ResourceManager.GetString("postChangeBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Supprimer.
        '''</summary>
        Friend Shared ReadOnly Property postDeleteBtn() As String
            Get
                Return ResourceManager.GetString("postDeleteBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Postes.
        '''</summary>
        Friend Shared ReadOnly Property postsBtn() As String
            Get
                Return ResourceManager.GetString("postsBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Poste.
        '''</summary>
        Friend Shared ReadOnly Property postsearchlabel() As String
            Get
                Return ResourceManager.GetString("postsearchlabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Postes.
        '''</summary>
        Friend Shared ReadOnly Property postTitle() As String
            Get
                Return ResourceManager.GetString("postTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mettre à jour.
        '''</summary>
        Friend Shared ReadOnly Property postUpdateBtn() As String
            Get
                Return ResourceManager.GetString("postUpdateBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Annuler.
        '''</summary>
        Friend Shared ReadOnly Property postUpdateCancelBtn() As String
            Get
                Return ResourceManager.GetString("postUpdateCancelBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mettre à jour.
        '''</summary>
        Friend Shared ReadOnly Property postUpdateValidationBtn() As String
            Get
                Return ResourceManager.GetString("postUpdateValidationBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Profil.
        '''</summary>
        Friend Shared ReadOnly Property profileBtn() As String
            Get
                Return ResourceManager.GetString("profileBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Profil.
        '''</summary>
        Friend Shared ReadOnly Property profileTitle() As String
            Get
                Return ResourceManager.GetString("profileTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Rafraîchir.
        '''</summary>
        Friend Shared ReadOnly Property refreshBtnE() As String
            Get
                Return ResourceManager.GetString("refreshBtnE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Rafraîchir.
        '''</summary>
        Friend Shared ReadOnly Property refreshBtnH() As String
            Get
                Return ResourceManager.GetString("refreshBtnH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Rafraîchir.
        '''</summary>
        Friend Shared ReadOnly Property refreshBtnP() As String
            Get
                Return ResourceManager.GetString("refreshBtnP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Rafraîchir.
        '''</summary>
        Friend Shared ReadOnly Property refreshBtnR() As String
            Get
                Return ResourceManager.GetString("refreshBtnR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Rafraîchir.
        '''</summary>
        Friend Shared ReadOnly Property refreshBtnU() As String
            Get
                Return ResourceManager.GetString("refreshBtnU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ajouter.
        '''</summary>
        Friend Shared ReadOnly Property roleAddBtn() As String
            Get
                Return ResourceManager.GetString("roleAddBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Annuler.
        '''</summary>
        Friend Shared ReadOnly Property roleAddCancelBtn() As String
            Get
                Return ResourceManager.GetString("roleAddCancelBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ajouter.
        '''</summary>
        Friend Shared ReadOnly Property roleAddValidationBtn() As String
            Get
                Return ResourceManager.GetString("roleAddValidationBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Supprimer.
        '''</summary>
        Friend Shared ReadOnly Property roleDeleteBtn() As String
            Get
                Return ResourceManager.GetString("roleDeleteBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Rôles.
        '''</summary>
        Friend Shared ReadOnly Property rolesBtn() As String
            Get
                Return ResourceManager.GetString("rolesBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Rôles.
        '''</summary>
        Friend Shared ReadOnly Property roleTitle() As String
            Get
                Return ResourceManager.GetString("roleTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mettre à jour.
        '''</summary>
        Friend Shared ReadOnly Property roleUpdateBtn() As String
            Get
                Return ResourceManager.GetString("roleUpdateBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Annuler.
        '''</summary>
        Friend Shared ReadOnly Property roleUpdateCancelBtn() As String
            Get
                Return ResourceManager.GetString("roleUpdateCancelBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mettre à jour.
        '''</summary>
        Friend Shared ReadOnly Property roleUpdateValidationBtn() As String
            Get
                Return ResourceManager.GetString("roleUpdateValidationBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Aucun résultat trouvé.
        '''</summary>
        Friend Shared ReadOnly Property searchErrorE() As String
            Get
                Return ResourceManager.GetString("searchErrorE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Aucun résultat trouvé.
        '''</summary>
        Friend Shared ReadOnly Property searchErrorH() As String
            Get
                Return ResourceManager.GetString("searchErrorH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Aucun résultat trouvé.
        '''</summary>
        Friend Shared ReadOnly Property searchErrorP() As String
            Get
                Return ResourceManager.GetString("searchErrorP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Aucun résultat trouvé.
        '''</summary>
        Friend Shared ReadOnly Property searchErrorR() As String
            Get
                Return ResourceManager.GetString("searchErrorR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Aucun résultat trouvé.
        '''</summary>
        Friend Shared ReadOnly Property searchErrorU() As String
            Get
                Return ResourceManager.GetString("searchErrorU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Rechercher un nom d&apos;utilisateur.
        '''</summary>
        Friend Shared ReadOnly Property searchuserlabel() As String
            Get
                Return ResourceManager.GetString("searchuserlabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Changer.
        '''</summary>
        Friend Shared ReadOnly Property stateChangeBtn() As String
            Get
                Return ResourceManager.GetString("stateChangeBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à État.
        '''</summary>
        Friend Shared ReadOnly Property statesearchlabel() As String
            Get
                Return ResourceManager.GetString("statesearchlabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Titre de l&apos;utilisateur:.
        '''</summary>
        Friend Shared ReadOnly Property TitleProfileLabel() As String
            Get
                Return ResourceManager.GetString("TitleProfileLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mettre l&apos;équipement à jour.
        '''</summary>
        Friend Shared ReadOnly Property updateEquipmentTitle() As String
            Get
                Return ResourceManager.GetString("updateEquipmentTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez remplir tous les champs.
        '''</summary>
        Friend Shared ReadOnly Property updateHallErrorMsg() As String
            Get
                Return ResourceManager.GetString("updateHallErrorMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nom de la salle.
        '''</summary>
        Friend Shared ReadOnly Property updateHallNameLabel() As String
            Get
                Return ResourceManager.GetString("updateHallNameLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mettre le poste à jour.
        '''</summary>
        Friend Shared ReadOnly Property updatePostTitle() As String
            Get
                Return ResourceManager.GetString("updatePostTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Annuler.
        '''</summary>
        Friend Shared ReadOnly Property updateProfileCancelBtn() As String
            Get
                Return ResourceManager.GetString("updateProfileCancelBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mettre à jour.
        '''</summary>
        Friend Shared ReadOnly Property updateProfileShowBtn() As String
            Get
                Return ResourceManager.GetString("updateProfileShowBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mettre le profil à jour.
        '''</summary>
        Friend Shared ReadOnly Property updateProfileTitle() As String
            Get
                Return ResourceManager.GetString("updateProfileTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mettre à jour.
        '''</summary>
        Friend Shared ReadOnly Property updateProfileValidationBtn() As String
            Get
                Return ResourceManager.GetString("updateProfileValidationBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez remplir tous les champs.
        '''</summary>
        Friend Shared ReadOnly Property updateRoleErrorMsg() As String
            Get
                Return ResourceManager.GetString("updateRoleErrorMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nom du Rôle.
        '''</summary>
        Friend Shared ReadOnly Property updateRoleNameLabel() As String
            Get
                Return ResourceManager.GetString("updateRoleNameLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à mettre le rôle à jour.
        '''</summary>
        Friend Shared ReadOnly Property updateRoleTitle() As String
            Get
                Return ResourceManager.GetString("updateRoleTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Courriel de l&apos;utilisateur.
        '''</summary>
        Friend Shared ReadOnly Property updateUserEmailLabel() As String
            Get
                Return ResourceManager.GetString("updateUserEmailLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nom de l&apos;utilisateur.
        '''</summary>
        Friend Shared ReadOnly Property updateUserNameLabel() As String
            Get
                Return ResourceManager.GetString("updateUserNameLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Numéro de téléphone de l&apos;utilisateur.
        '''</summary>
        Friend Shared ReadOnly Property updateUserPhoneLabel() As String
            Get
                Return ResourceManager.GetString("updateUserPhoneLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mettre l&apos;utilisateur à jour.
        '''</summary>
        Friend Shared ReadOnly Property updateUserTitle() As String
            Get
                Return ResourceManager.GetString("updateUserTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Titre de l&apos;utilisateur.
        '''</summary>
        Friend Shared ReadOnly Property updateUserTitleLabel() As String
            Get
                Return ResourceManager.GetString("updateUserTitleLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ajouter.
        '''</summary>
        Friend Shared ReadOnly Property userAddBtn() As String
            Get
                Return ResourceManager.GetString("userAddBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Annuler.
        '''</summary>
        Friend Shared ReadOnly Property userAddCancelBtn() As String
            Get
                Return ResourceManager.GetString("userAddCancelBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ajouter.
        '''</summary>
        Friend Shared ReadOnly Property userAddValidationBtn() As String
            Get
                Return ResourceManager.GetString("userAddValidationBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Confirmez le mot de passe.
        '''</summary>
        Friend Shared ReadOnly Property userConfirmPwdProfileLabel() As String
            Get
                Return ResourceManager.GetString("userConfirmPwdProfileLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Supprimer.
        '''</summary>
        Friend Shared ReadOnly Property userDeleteBtn() As String
            Get
                Return ResourceManager.GetString("userDeleteBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à E-mail de l&apos;utilisateur.
        '''</summary>
        Friend Shared ReadOnly Property userEmailProfileLabel2() As String
            Get
                Return ResourceManager.GetString("userEmailProfileLabel2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nom de l&apos;utilisateur.
        '''</summary>
        Friend Shared ReadOnly Property userNameProfileLabel2() As String
            Get
                Return ResourceManager.GetString("userNameProfileLabel2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Numéro de téléphone de l&apos;utilisateur.
        '''</summary>
        Friend Shared ReadOnly Property userPhoneNumberProfileLabel2() As String
            Get
                Return ResourceManager.GetString("userPhoneNumberProfileLabel2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Entrez le mot de passe.
        '''</summary>
        Friend Shared ReadOnly Property userPwdProfileLabel() As String
            Get
                Return ResourceManager.GetString("userPwdProfileLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Utilisateurs.
        '''</summary>
        Friend Shared ReadOnly Property usersBtn() As String
            Get
                Return ResourceManager.GetString("usersBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Voir.
        '''</summary>
        Friend Shared ReadOnly Property usersBtn2() As String
            Get
                Return ResourceManager.GetString("usersBtn2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Utilisateurs.
        '''</summary>
        Friend Shared ReadOnly Property userTitle() As String
            Get
                Return ResourceManager.GetString("userTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Administrateurs.
        '''</summary>
        Friend Shared ReadOnly Property userTypeTitle() As String
            Get
                Return ResourceManager.GetString("userTypeTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Utilisateurs.
        '''</summary>
        Friend Shared ReadOnly Property userTypeTitleU() As String
            Get
                Return ResourceManager.GetString("userTypeTitleU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mettre à jour.
        '''</summary>
        Friend Shared ReadOnly Property userUpdateBtn() As String
            Get
                Return ResourceManager.GetString("userUpdateBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Annuler.
        '''</summary>
        Friend Shared ReadOnly Property userUpdateCancelBtn() As String
            Get
                Return ResourceManager.GetString("userUpdateCancelBtn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mettre à jour.
        '''</summary>
        Friend Shared ReadOnly Property userUpdateValidationBtn() As String
            Get
                Return ResourceManager.GetString("userUpdateValidationBtn", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
